#!/bin/sh

mkdir web
rm web/* 
mogrify  -define jpeg -resize 480x288 -auto-orient -unsharp 0x.5 -path web  * 

mkdir th
rm th/* 
mogrify  -define jpeg:size=500x180 -auto-orient  -thumbnail 250x90 -unsharp 0x.5 -path th  * 

